### ISSUE TITLE
xcenv: no such command `shell'

### ISSUE THREAD

**Issue by JanC** [xcenv/xcenv#11]
- [x] I have read the [Contribution Guidelines](https://github.com/xcenv/xcenv/blob/master/CONTRIBUTING.md)
### Description

Hi,
The command `xcenv shell` does not seem to work in the version 1.0.4

[Description of the bug or feature]
### Versions

OSX El Capitan
### Steps to Reproduce

```
brew install xcenv
xcenv shell 7.3.1
```

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

```
xcenv: no such command `shell'
```

**Comment by JanC** [comment]
Nevermind, I forgot to use `eval "$(xcenv init -)"` in my .bashrc

**Comment by maschall** [comment]
Thanks @JanC.  If there you think we need more documentation please let me know!

**Comment by JanC** [comment]
not at all .. It's just me who didn't read the readme :)
