### ISSUE TITLE
`xcenv` does not affect the result of `xcode-select -p`

### ISSUE THREAD

**Issue by manicmaniac** [xcenv/xcenv#14]
- [x] I have read the [Contribution Guidelines](https://github.com/xcenv/xcenv/blob/master/CONTRIBUTING.md)

### Description

`xcenv` does not affect the result of `xcode-select -p`.

I'm afraid this may break some tools like fastlane, which use `xcode-select -p` to get the path of Xcode.

https://github.com/fastlane/fastlane/blob/05597f5e3f93d3808b3c6b8794052df44192cf4d/fastlane_core/lib/fastlane_core/helper.rb#L110

### Versions

xcenv 1.1.0
It reproduces at least on Mac OS X, Xcode [6.1|7.3.1|8.1]

### Steps to Reproduce

1. `sudo xcode-select -s /Applications/Xcode6.1.app/Contents/Developer`
2. `xcenv local 8.1` or `xcenv shell 8.1`
3. `xcode-select -p`

**Expected behavior:** [What you expected to happen]

Step 3 shows `/Applications/Xcode8.1.app/Contents/Developer`

**Actual behavior:** [What actually happened]

Step 3 shows `/Applications/Xcode6.1.app/Contents/Developer`

`xcode-select` always ignores `xcenv`.

**Comment by maschall** [comment]
Thanks @manicmaniac for the report!

Originally, we were doing this, but then I had decided against it to support the ability to set `system` as the version to use, which would use the results of `xcode-select -p`, so we had blacklisted xcode-select.

After thinking about it, I think we can support this, we just need to make sure that `sudo xcode-select -s` still works appropriately.

Thanks again for the report, I'll look at adding it back to xcenv.
