### ISSUE TITLE
Xcode 9.1 not detected

### ISSUE THREAD

**Issue by JanC** [xcenv/xcenv#16]
- [x] I have read the [Contribution Guidelines](https://github.com/xcenv/xcenv/blob/master/CONTRIBUTING.md)

### Description
`xcenv` is not detecting XCode 9.1

### Versions
Xcode 7.3.1
Xcode 8.3.3
Xcode 9.1

### Steps to Reproduce
I downloaded Xcode 9.1 from the dev portal and installed it in /Applcations. `xcenv` is detecting other XCode versions except the 9.1:
```
xcenv rehash
xcenv versions
8.3.3
7.3.1

xcenv xcodes
/Applications/Xcode.app
/Applications/Xcode7.3.app

ls -al /Applications/
Xcode.app
Xcode7.3.app
Xcode9.1.app

 xcode-select -p
/Applications/Xcode9.1.app/Contents/Developer

 xcenv version
/Applications/Xcode9.1.app/ (set by system)
```

**Comment by maschall** [comment]
Thanks for the report.  

`xcenv` currently relies on Spotlight to find all the xcodes.  The intention was to support non-`/Applications` installs of Xcode.  Thinking about it now, maybe we should add back some common install locations like `/Applications` as a always check.

Could you try opening Xcode 9 via Spotlight, and then try `xcenv versions`, just to see if that resolves your instance?

**Comment by JanC** [comment]
Opening Xcode via Spotlight did not help but re-indexing did!

`mdfind "kMDItemCFBundleIdentifier == 'com.apple.dt.Xcode'"` was still returning only the two older XCodes. 

I re-indexed Spotlight using `sudo mdutil -Ea`

now it all works:
```
xcenv xcodes
/Applications/Xcode.app
/Applications/Xcode7.3.app
/Applications/Xcode9.1.app
```

Thanks!
