### ISSUE TITLE
Use lastest `git` from brew

### ISSUE THREAD

**Issue by Whirlwind** [xcenv/xcenv#18]
Apple Git is from Xcode, it is older. I want to use newer version, so I exec `brew install git`.

But now the git in the brew will not work. The `PATH` of xcenv is front of `/usr/local/bin`:

```
$ echo $PATH
/Users/whirlwind/.rvm/gems/ruby-2.4.1/bin:/Users/whirlwind/.rvm/gems/ruby-2.4.1@global/bin:/Users/whirlwind/.rvm/rubies/ruby-2.4.1/bin:/Users/whirlwind/.xcenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/whirlwind/.rvm/bin
```

**Comment by nikolaykasyanov** [comment]
Blacklisting git shims should help https://github.com/xcenv/xcenv#xcenv_do_not_shim_list.

**Comment by Whirlwind** [comment]
great
