### ISSUE TITLE
Homebrew repository is not accessible

### ISSUE THREAD

**Issue by bojan** [xcenv/xcenv#9]
The Homebrew repository (https://github.com/xcenv/homebrew-xcenv) is a private one.

It is not possible to access it using Homebrew, git or in the browser, making the installation instructions broken.

**Comment by maschall** [comment]
@bojan Thanks for the report.  I forgot to update the Readme.  We were able to get accepted into homebrew-core, so the command is now just `brew install xcenv`.  Thanks again!

**Comment by maschall** [comment]
Resolved in 93bcc94
